name: Build WebViewExtra

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Install Rush CLI
        run: |
          curl -fsSL https://raw.githubusercontent.com/ShreyashSaitwal/rush-cli/main/install.sh | bash
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Check Rush
        run: rush --version

      - name: Build extension
        run: rush build

      - name: Upload AIX
        uses: actions/upload-artifact@v4
        with:
          name: WebViewExtra
          path: |
            **/*.aix
